// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAPI2.Data;

#nullable disable

namespace WebAPI2.Migrations
{
    [DbContext(typeof(SchoolDbContext))]
    [Migration("20250623112412_AddRecordsToStudentsTable")]
    partial class AddRecordsToStudentsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebAPI2.Data.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "port 11, esville, ah, riv, ng, af",
                            DateOfBirth = new DateOnly(2000, 4, 13),
                            Email = "yej@jey.com",
                            Name = "yej"
                        },
                        new
                        {
                            Id = 2,
                            Address = "port 11, esville, ah, riv, ng, af",
                            DateOfBirth = new DateOnly(2006, 4, 7),
                            Email = "uk@okey.com",
                            Name = "uk"
                        },
                        new
                        {
                            Id = 3,
                            Address = "port 13, esville, ah, riv, ng, af",
                            DateOfBirth = new DateOnly(2001, 3, 28),
                            Email = "josh@yeshua.com",
                            Name = "josh"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
