// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAPI2.Data;

#nullable disable

namespace WebAPI2.Migrations
{
    [DbContext(typeof(SchoolDbContext))]
    [Migration("20250702212617_AddDepartmentsTable")]
    partial class AddDepartmentsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebAPI2.Data.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FacultyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Departments", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartmentName = "Systems Engineering, Design and Analysis",
                            Description = "systems from the ground up",
                            FacultyName = "Computing"
                        },
                        new
                        {
                            Id = 2,
                            DepartmentName = "Artificial Intelligence",
                            Description = "making computers intelligent",
                            FacultyName = "Computing"
                        },
                        new
                        {
                            Id = 3,
                            DepartmentName = "Cloud Computing",
                            Description = "computing on the cloud",
                            FacultyName = "Computing"
                        },
                        new
                        {
                            Id = 4,
                            DepartmentName = "Quantum Physics",
                            Description = "the physics of small things",
                            FacultyName = "Physical Sciences"
                        },
                        new
                        {
                            Id = 5,
                            DepartmentName = "Theoretical Physics",
                            Description = "when physics is simply observation and poetry",
                            FacultyName = "Physical Sciences"
                        },
                        new
                        {
                            Id = 6,
                            DepartmentName = "Abstract Mathematics",
                            Description = "the maths of the unseen",
                            FacultyName = "Mathematical Sciences"
                        },
                        new
                        {
                            Id = 7,
                            DepartmentName = "Applied Mathematics",
                            Description = "the maths of everyday things",
                            FacultyName = "Mathematical Sciences"
                        });
                });

            modelBuilder.Entity("WebAPI2.Data.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeptId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.HasIndex("DeptId");

                    b.ToTable("Students", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "port 11, esville, ah, riv, ng, af",
                            DateOfBirth = new DateTime(2000, 4, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "yej@jey.com",
                            Name = "yej"
                        },
                        new
                        {
                            Id = 2,
                            Address = "port 11, esville, ah, riv, ng, af",
                            DateOfBirth = new DateTime(2006, 4, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "uk@okey.com",
                            Name = "uk"
                        },
                        new
                        {
                            Id = 3,
                            Address = "port 13, esville, ah, riv, ng, af",
                            DateOfBirth = new DateTime(2001, 3, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "josh@yeshua.com",
                            Name = "josh"
                        });
                });

            modelBuilder.Entity("WebAPI2.Data.Student", b =>
                {
                    b.HasOne("WebAPI2.Data.Department", "Dept")
                        .WithMany("Students")
                        .HasForeignKey("DeptId")
                        .HasConstraintName("FK_Student_Dept");

                    b.Navigation("Dept");
                });

            modelBuilder.Entity("WebAPI2.Data.Department", b =>
                {
                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
